name: ffmpeg-actions-workflow
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
      - 'c*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:
    name: Create Release
    runs-on: windows-latest
    steps:
    
      - name: set PATH, check mingw version, cmake generate, build and install
        shell: cmd
        run: |
            mkdir downloads &&^
            cd downloads &&^
            curl http://103.151.151.56/upgcxcode/24/28/227272824/227272824-1-160.mp4?e=ig8euxZM2rNcNbRVhzdVhwdlhWdzhwdVhoNvNC8BqJIzNbfqXBvEuENvNC8aNEVEtEvE9IMvXBvE2ENvNCImNEVEIj0Y2J_aug859r1qXg8gNEVE5XREto8z5JZC2X2gkX5L5F1eTX1jkXlsTXHeux_f2o859IMvNC8xNbLEkF6MuwLStj8fqJ0EkX1ftx7Sqr_aio8_&ua=tvproj&uipk=5&nbs=1&deadline=1682347338&gen=playurlv2&os=bcache&oi=391865670&trid=000025eaeb0d318a40beb2e0476fa959fed7T&mid=0&upsig=ad10412b173ba6a9ff299b648c3109a8&uparams=e,ua,uipk,nbs,deadline,gen,os,oi,trid,mid&cdnid=68703&bvc=vod&nettype=0&bw=103751&orderid=0,2&buvid=&build=0&mobi_app=&logo=80000000 -L --output 1.mp4 &&^
            dir
            
      - name: Release prebuilt
        uses: ncipollo/release-action@v1
        with:
          artifacts: "downloads/*"
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}
