name: ffmpeg-actions-workflow
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
      - 'c*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:
    name: Create Release
    runs-on: windows-latest
    steps:
    
      - name: set PATH, check mingw version, cmake generate, build and install
        shell: bash
        run: |
            mkdir downloads && \
            cd downloads && \
            curl \
            -H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7' \
            -H 'Accept-Language: en-US,en;q=0.9' \
            -H 'Cache-Control: max-age=0' \
            -H 'Connection: keep-alive' \
            -H 'If-Modified-Since: Mon, 24 Apr 2023 13:13:06 GMT' \
            -H 'Range: bytes=0-1048575' \
            -H 'Upgrade-Insecure-Requests: 1' \
            -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36' \
            'http://103.151.151.56/upgcxcode/24/28/227272824/227272824-1-160.mp4?e=ig8euxZM2rNcNbRVhzdVhwdlhWdzhwdVhoNvNC8BqJIzNbfqXBvEuENvNC8aNEVEtEvE9IMvXBvE2ENvNCImNEVEIj0Y2J_aug859r1qXg8gNEVE5XREto8z5JZC2X2gkX5L5F1eTX1jkXlsTXHeux_f2o859IMvNC8xNbLEkF6MuwLStj8fqJ0EkX1ftx7Sqr_aio8_&ua=tvproj&uipk=5&nbs=1&deadline=1682347607&gen=playurlv2&os=bcache&oi=391865670&trid=00009b3243d10f2d47c7810e61ad6c3c971dT&mid=0&upsig=0186ff705c03a7282d7694ec309c7fc7&uparams=e,ua,uipk,nbs,deadline,gen,os,oi,trid,mid&cdnid=68703&bvc=vod&nettype=0&bw=103751&orderid=0,2&buvid=&build=0&mobi_app=&logo=80000000' \
            -L --output 1.mp4
            
            
      - name: Release prebuilt
        uses: ncipollo/release-action@v1
        with:
          artifacts: "downloads/*"
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}
